"""Tests for scripts/generate_synthetic_data.py (legacy and v2 profiles).

Two guarantees are locked down here:

1. ``--profile legacy`` still produces exactly what it produced before the v2
   work.  Note that ``data/synthetic/`` was generated by an *older* revision of
   the script -- one that sampled ``elevation = uniform(-30, 30)`` before the
   "84% oblique" bias landed -- so its camera geometry no longer matches the
   current legacy code.  The pose/shape random stream is unchanged, and that
   part is checked against the on-disk anchor; the camera geometry and proxy
   tensor are checked against golden values captured from the pre-refactor
   script (commit 5f982bb, scripts/generate_synthetic_data.py), which the
   refactored code reproduces bit-for-bit.

2. ``--profile v2`` is genuinely articulated, projects through the fixed
   focal-1000 pinhole that SPIN/SMPLify assume, and frames every joint inside
   the letterbox band of its sampled source aspect.

3. ``--profile v3`` changes exactly ONE thing about v2 -- the focal length is
   drawn per sample instead of pinned -- and says so on disk.  The "one thing"
   claim is tested the only way it can be: a v3 run with the focal pinned back
   to 1000 reproduces the v2 run of the same seed bit for bit.

4. ``scripts/merge_synthetic_sets.py`` puts the two conventions in one index
   without copying a byte, and its sidecar reports the bimodal focal range a
   focal-conditioned training run stamps into its checkpoints.
"""
from __future__ import annotations
import json
import sys
from pathlib import Path
import numpy as np
import pytest
import torch
from shark_pose.core.camera import PerspectiveCamera
from shark_pose.core.constants import DEFAULT_HEATMAP_SIGMA
from shark_pose.core.skeleton import BONE_PAIRS
from generate_synthetic_data import V2_FOCAL_LENGTH, V2_SOURCE_ASPECTS, V2_SPAN_RANGE_PX, V3_FOCAL_RANGE_PX, generate_dataset
LEGACY_PROXY_SUM = 904.7714649438858
LEGACY_PROXY_NNZ = 15671
RESOLUTION = 256
X_LIMITS = (4.0, 252.0)

def _load(sample_dir: Path, sample_id: str):
    ...

@requires_assets
@requires_anchor
def test_legacy_profile_is_unchanged(tmp_path):
    """The default (legacy) path must be bit-stable."""
    ...

@requires_assets
def test_v2_profile(tmp_path):
    """Profile v2: articulated, SPIN-consistent, band-framed."""
    ...

@requires_assets
def test_v2_profile_is_reproducible(tmp_path):
    """Same seed -> same v2 sample, independent of the FK batching."""
    ...

@requires_assets
def test_v3_pinned_to_the_v2_focal_reproduces_v2(tmp_path):
    """v3 changes TWO things: the focal draw and the camera span refinement.

    The focal comes off its own random stream, so pinning the range to the v2
    focal and switching the refinement off must give back the v2 sample --
    same joints, same heatmaps, same camera, byte for byte -- with only the
    recorded profile differing.  With the refinement left at its v3 default
    the same pinned draw must still move at least one sample: the refinement
    is a real (v3-only) part of the recipe, not a no-op.  If either half fails,
    a v2-vs-v3 comparison is confounded by something other than the camera.
    """
    ...

def test_focal_range_is_v3_only(tmp_path):
    ...

@requires_assets
def test_v3_profile(tmp_path):
    """v3: focal sampled per sample, stored, and consistent with the stored 2D."""
    ...

@requires_assets
def test_v2_writes_metadata_pinned_at_1000(tmp_path):
    """A v2 set gets the same sidecar, saying its focal never moves."""
    ...

@requires_assets
def test_merged_set_references_both_sample_sets(tmp_path):
    """The merged index points at both sets and reports a bimodal focal range.

    The merged directory holds two JSON files and no sample data: every entry
    points at the file the source set already wrote, which is what makes
    merging two 24 GB sets cost kilobytes.  The focal statistics
    ``scripts/train_spin.py::dataset_focal_stats`` reads must then span BOTH
    conventions -- the 1000 px pinhole and the 110-230 px range -- because that
    range is what a focal-conditioned checkpoint is stamped with.
    """
    ...

def test_merge_refuses_a_single_source(tmp_path):
    ...

def test_unknown_profile_rejected(tmp_path):
    ...

def test_default_heatmap_sigma_is_the_generator_default():
    """generate_proxy_tensor must keep using the repo-wide sigma."""
    ...
